name: melon_ticket_0412
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: ${{ secrets.MELON_TICKET_PRODUCT_ID }}
          schedule-id: ${{ secrets.MELON_TICKET_SCHEDULE_ID }}
          # seat-id: 1_0
          # slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          interval: 300  # 检查间隔（秒）
          message: '<@U4CF18RKL> 티켓사세요'
